### ISSUE TITLE
Listing LDC Token

### ISSUE THREAD

**Issue by 7sxnc** [OpenTokenRegistry/otr.cash#14]
I'm trying to create this pull request:

# New Listing: `LDC` 

- Identity Name: Limones Digital Coin
- Authbase: 4d621027246ae61b3de5887e69523eebcc4e3d6e7e031a2aa6010ccc5272ed08

## Evidence Linking Authbase to Identity

- **Select one**:
  - [X] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below:
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities) or provably locked within a covenant, so the authbase can safely be linked using indirect evidence. Details and two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:

## Evidence Linking Authbase to Categories

- **Select one**:
  - [X] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

 Proof: https://explorer.salemkode.com/tx/4d621027246ae61b3de5887e69523eebcc4e3d6e7e031a2aa6010ccc5272ed08

## Substantiation of Other Claims

- **Select one**:
  - [X] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

# Checklist

- [X] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [X] The listing completes all required fields:
  - **`name`**
    - [X] Objective, authoritative, and neutral tone
    - [X] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [X] Objective, authoritative, and neutral tone
    - [X] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [X] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [X] Token `category` is defined.
    - [X] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [X] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [X] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [X] Appropriate minimum length (For new, primarily-fungible base symbols: minimum of 4 characters; non-fungible base symbols: minimum of 6 characters; see [Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip/#symbol-length-recommendations))
      - [X] No longer than 13 characters for base symbols
      - [X] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [X] Uses IPFS with a v1 CID. To convert a v0 CID (begins with `Qm...`), try `dweb.link`. For example, `bafybeifv5l6foaqrxeux4dl7mj55d4a4lsthbrsyba3v6yqtarzbxcmn2m` is a v0 CID. It can be viewed at `https://d391b93f5f62d9c15f67142e43841acc.ipfscdn.io/ipfs/bafybeifv5l6foaqrxeux4dl7mj55d4a4lsthbrsyba3v6yqtarzbxcmn2m/a21966af10fabce599678eb258e69158.png`, which redirects to a subdomain equal to the v1 CID: `https://d391b93f5f62d9c15f67142e43841acc.ipfscdn.io/`. The correct URI for this icon is: `ipfs://QmaanKpq3bsHUrpJuASynqDurDeQbTYz6v35BLaD2BDmzS/a21966af10fabce599678eb258e69158.png`.
    - [X] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`https://limonia.org`**
  - **`https://bcl.limonia.org/en`**
    - [X] Domain name is owned by the issuing project or organization
    - [X] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [X] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [X] All static data (images, animations, videos, binary files, etc.) uses `IPFS` with v1 CIDs to ensure file integrity (e.g. `ipfs://ba...`).

**Comment by georgedonnelly** [comment]
You created this as an issue but it should be a pull request. You can follow this documentation and/or feel free to request help in https://t.me/cashtoken_devs. I think we would love to assist you there.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

BTW you don't seem to have chain-resolved metadata for either of the hashes in your issue.

I am closing this.
